CUDA_VISIBLE_DEVICES=0 \
swift sft \
    --model /home/xli/models/InternVL3-14B \
    --train_type lora \
    --dataset /home/xli/skw/Visual_QA/complex_flowchart/Train/data/sft_data/Qwen2.5_vl_sft_data/Flowchart_Bench_v4.json \
    --torch_dtype bfloat16 \
    --num_train_epochs 1 \
    --per_device_train_batch_size 1 \
    --learning_rate 5e-4 \
    --lora_rank 64 \
    --lora_alpha 64 \
    --target_modules all-linear \
    --gradient_accumulation_steps 32 \
    --save_strategy epoch \
    --save_total_limit 1\
    --logging_steps 1 \
    --max_length 5120 \
    --output_dir output/Flowchart_Bench_v4_5e_4_ga_32\
    --warmup_ratio 0.05 \
    --dataloader_num_workers 4 \
    --report_to none \
    --attn_impl flash_attn\
